name: Deploy Tasky Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tasky
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cfn/cfn-wiz.yaml \
            --stack-name tasky-${{ github.ref_name }} \
            --parameter-overrides KeyName=wiz-keypair.pem \
            --capabilities CAPABILITY_IAM
            
      - name: Update EKS deployment
        run: |
          aws eks update-kubeconfig --name eks-cluster --region us-east-1
          kubectl set image deployment/tasky-mongodb tasky=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
