name: Deploy Security Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'cfn/cfn-cf-waf-shield.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        id: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: tasky-security
          template: cfn/cfn-cf-waf-shield.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            AlbDnsName=${{ secrets.ALB_ENDPOINT }},
            ExistingS3BucketName=${{ secrets.S3_BUCKET_NAME }},
            EnableGuardDuty=true
