name: Deploy Security Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'cfn/cfn-cf-waf-shield.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy a CloudFormation stack
        id: deploy
        run: |
          aws cloudformation deploy \
            --template-file cfn/cfn-cf-waf-shield.yaml \
            --stack-name tasky-security \
            --parameter-overrides \
              AlbDnsName=${{ secrets.ALB_ENDPOINT }} \
              ExistingS3BucketName=${{ secrets.S3_BUCKET_NAME }} \
              EnableGuardDuty=true \
            --no-fail-on-empty-changeset

      - name: Get CloudFront domain
        if: success()
        run: |
          CF_DOMAIN=$(aws cloudformation describe-stacks --stack-name tasky-security --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDomain'].OutputValue" --output text)
          echo "CloudFront domain: $CF_DOMAIN"
          echo "CLOUDFRONT_DOMAIN=$CF_DOMAIN" >> $GITHUB_ENV
